"""Reference freight rate cards.

International corridors are priced in USD per chargeable kg, domestic legs in
RUB per chargeable kg.  Figures are 2025–2026 market benchmarks for consolidated
(LTL/сборный) cargo and must be refreshed from live forwarder quotes for
production use.  ``CARGO_ALL_IN`` cards already include the cargo company's
simplified clearance and handling; ``WHITE_FREIGHT`` cards are pure transport
plus hub handling and are combined with official customs clearance.
"""

from __future__ import annotations

from decimal import Decimal

from ved_calculator.domain.models import (
    CargoCategory,
    CorridorRateCard,
    DomesticLegRate,
    OriginCountry,
    ServiceKind,
    TransportMode,
)

BISHKEK = "Bishkek"
MOSCOW = "Moscow"

_CARGO_MULTIPLIERS = {
    CargoCategory.ELECTRONICS: Decimal("1.35"),
    CargoCategory.APPAREL: Decimal("0.95"),
}
_AIR_CARGO_MULTIPLIERS = {CargoCategory.ELECTRONICS: Decimal("1.25")}


def _card(
    corridor_id: str,
    origin: OriginCountry,
    origin_hub: str,
    destination_hub: str,
    mode: TransportMode,
    kind: ServiceKind,
    rate: str,
    min_charge: str,
    coefficient: str,
    days: tuple[int, int],
    *,
    handling_fixed: str = "0",
    handling_per_kg: str = "0",
    multipliers: dict[CargoCategory, Decimal] | None = None,
    notes: str = "",
) -> CorridorRateCard:
    return CorridorRateCard(
        corridor_id=corridor_id,
        origin=origin,
        origin_hub=origin_hub,
        destination_hub=destination_hub,
        transport_mode=mode,
        service_kind=kind,
        rate_per_kg_usd=Decimal(rate),
        min_charge_usd=Decimal(min_charge),
        volumetric_coefficient_kg_per_m3=Decimal(coefficient),
        handling_fixed_usd=Decimal(handling_fixed),
        handling_per_kg_usd=Decimal(handling_per_kg),
        days_min=days[0],
        days_max=days[1],
        category_multipliers=multipliers or {},
        notes=notes,
    )


_CN = OriginCountry.CHINA
_TR = OriginCountry.TURKEY
_EU = OriginCountry.EU
_US = OriginCountry.USA
_AE = OriginCountry.UAE
_VN = OriginCountry.VIETNAM
_W = ServiceKind.WHITE_FREIGHT
_C = ServiceKind.CARGO_ALL_IN
_M = TransportMode

DEFAULT_CORRIDORS: tuple[CorridorRateCard, ...] = (
    # ---------------------------------------------------------------- China → Bishkek
    _card(
        "CN-FRU-AUTO-EXPRESS-CARGO",
        _CN,
        "Guangzhou / Yiwu",
        BISHKEK,
        _M.AUTO_EXPRESS,
        _C,
        "3.40",
        "150",
        "200",
        (10, 15),
        multipliers=_CARGO_MULTIPLIERS,
        notes="Cargo express truck via Kashgar–Torugart/Irkeshtam, all-in $/kg",
    ),
    _card(
        "CN-FRU-AUTO-STANDARD-CARGO",
        _CN,
        "Guangzhou / Yiwu",
        BISHKEK,
        _M.AUTO_STANDARD,
        _C,
        "2.90",
        "120",
        "200",
        (16, 25),
        multipliers=_CARGO_MULTIPLIERS,
        notes="Cargo standard truck (consolidated), all-in $/kg",
    ),
    _card(
        "CN-FRU-AIR-CARGO",
        _CN,
        "Guangzhou",
        BISHKEK,
        _M.AIR,
        _C,
        "5.20",
        "250",
        "167",
        (5, 8),
        multipliers=_AIR_CARGO_MULTIPLIERS,
        notes="Cargo air consolidation CAN/URC → FRU",
    ),
    _card(
        "CN-FRU-AUTO-EXPRESS-WHITE",
        _CN,
        "Guangzhou / Yiwu",
        BISHKEK,
        _M.AUTO_EXPRESS,
        _W,
        "1.90",
        "400",
        "250",
        (10, 14),
        handling_fixed="80",
        handling_per_kg="0.08",
        notes="Official LTL express truck with CMR/invoice for declaration",
    ),
    _card(
        "CN-FRU-AUTO-STANDARD-WHITE",
        _CN,
        "Guangzhou / Yiwu",
        BISHKEK,
        _M.AUTO_STANDARD,
        _W,
        "1.35",
        "350",
        "250",
        (16, 22),
        handling_fixed="80",
        handling_per_kg="0.08",
        notes="Official LTL standard truck",
    ),
    _card(
        "CN-FRU-RAIL-WHITE",
        _CN,
        "Guangzhou / Yiwu",
        BISHKEK,
        _M.RAIL,
        _W,
        "1.05",
        "900",
        "300",
        (20, 30),
        handling_fixed="120",
        handling_per_kg="0.08",
        notes="Rail via Dostyk/Altynkol → Almaty, truck on-carriage to Bishkek",
    ),
    _card(
        "CN-FRU-AIR-WHITE",
        _CN,
        "Guangzhou",
        BISHKEK,
        _M.AIR,
        _W,
        "4.30",
        "500",
        "167",
        (4, 7),
        handling_fixed="80",
        handling_per_kg="0.10",
        notes="Official air freight with AWB",
    ),
    # ---------------------------------------------------------------- China → Moscow (benchmark)
    _card(
        "CN-MOW-AUTO-STANDARD-WHITE",
        _CN,
        "Guangzhou / Yiwu",
        MOSCOW,
        _M.AUTO_STANDARD,
        _W,
        "2.20",
        "600",
        "250",
        (18, 25),
        handling_fixed="100",
        handling_per_kg="0.08",
    ),
    _card(
        "CN-MOW-RAIL-WHITE",
        _CN,
        "Guangzhou / Yiwu",
        MOSCOW,
        _M.RAIL,
        _W,
        "1.50",
        "1200",
        "300",
        (25, 35),
        handling_fixed="150",
        handling_per_kg="0.08",
    ),
    _card(
        "CN-MOW-AIR-WHITE",
        _CN,
        "Guangzhou",
        MOSCOW,
        _M.AIR,
        _W,
        "5.60",
        "600",
        "167",
        (5, 9),
        handling_fixed="100",
        handling_per_kg="0.10",
    ),
    # ---------------------------------------------------------------- Turkey → Bishkek
    _card(
        "TR-FRU-AUTO-STANDARD-CARGO",
        _TR,
        "Istanbul",
        BISHKEK,
        _M.AUTO_STANDARD,
        _C,
        "1.90",
        "120",
        "200",
        (12, 18),
        multipliers=_CARGO_MULTIPLIERS,
    ),
    _card(
        "TR-FRU-AIR-CARGO",
        _TR,
        "Istanbul",
        BISHKEK,
        _M.AIR,
        _C,
        "4.20",
        "200",
        "167",
        (3, 6),
        multipliers=_AIR_CARGO_MULTIPLIERS,
    ),
    _card(
        "TR-FRU-AUTO-STANDARD-WHITE",
        _TR,
        "Istanbul",
        BISHKEK,
        _M.AUTO_STANDARD,
        _W,
        "1.60",
        "400",
        "250",
        (12, 18),
        handling_fixed="80",
        handling_per_kg="0.08",
    ),
    _card(
        "TR-FRU-AIR-WHITE",
        _TR,
        "Istanbul",
        BISHKEK,
        _M.AIR,
        _W,
        "4.00",
        "450",
        "167",
        (3, 6),
        handling_fixed="80",
        handling_per_kg="0.10",
    ),
    # ---------------------------------------------------------------- Turkey → Moscow (benchmark)
    _card(
        "TR-MOW-AUTO-STANDARD-WHITE",
        _TR,
        "Istanbul",
        MOSCOW,
        _M.AUTO_STANDARD,
        _W,
        "1.70",
        "500",
        "250",
        (8, 14),
        handling_fixed="100",
        handling_per_kg="0.08",
    ),
    _card(
        "TR-MOW-AIR-WHITE",
        _TR,
        "Istanbul",
        MOSCOW,
        _M.AIR,
        _W,
        "3.80",
        "450",
        "167",
        (3, 5),
        handling_fixed="100",
        handling_per_kg="0.10",
    ),
    # ---------------------------------------------------------------- EU → Bishkek
    _card(
        "EU-FRU-AUTO-STANDARD-CARGO",
        _EU,
        "Warsaw / Berlin",
        BISHKEK,
        _M.AUTO_STANDARD,
        _C,
        "2.60",
        "150",
        "200",
        (18, 28),
        multipliers=_CARGO_MULTIPLIERS,
    ),
    _card(
        "EU-FRU-AIR-CARGO",
        _EU,
        "Frankfurt",
        BISHKEK,
        _M.AIR,
        _C,
        "6.00",
        "250",
        "167",
        (5, 9),
        multipliers=_AIR_CARGO_MULTIPLIERS,
    ),
    _card(
        "EU-FRU-AUTO-STANDARD-WHITE",
        _EU,
        "Warsaw / Berlin",
        BISHKEK,
        _M.AUTO_STANDARD,
        _W,
        "2.40",
        "600",
        "250",
        (18, 28),
        handling_fixed="80",
        handling_per_kg="0.08",
        notes="Truck via Georgia–Azerbaijan–Caspian or Kazakhstan transit",
    ),
    _card(
        "EU-FRU-AIR-WHITE",
        _EU,
        "Frankfurt",
        BISHKEK,
        _M.AIR,
        _W,
        "5.80",
        "600",
        "167",
        (5, 8),
        handling_fixed="80",
        handling_per_kg="0.10",
    ),
    # ---------------------------------------------------------------- EU → Moscow (benchmark)
    _card(
        "EU-MOW-AUTO-STANDARD-WHITE",
        _EU,
        "Warsaw / Berlin",
        MOSCOW,
        _M.AUTO_STANDARD,
        _W,
        "2.80",
        "700",
        "250",
        (20, 30),
        handling_fixed="100",
        handling_per_kg="0.08",
        notes="Parallel-import routing via third countries",
    ),
    _card(
        "EU-MOW-AIR-WHITE",
        _EU,
        "Frankfurt",
        MOSCOW,
        _M.AIR,
        _W,
        "6.50",
        "700",
        "167",
        (6, 10),
        handling_fixed="100",
        handling_per_kg="0.10",
    ),
    # ---------------------------------------------------------------- USA → Bishkek
    _card(
        "US-FRU-AIR-CARGO",
        _US,
        "New York / Los Angeles",
        BISHKEK,
        _M.AIR,
        _C,
        "8.50",
        "300",
        "167",
        (8, 14),
        multipliers=_AIR_CARGO_MULTIPLIERS,
    ),
    _card(
        "US-FRU-AIR-WHITE",
        _US,
        "New York / Los Angeles",
        BISHKEK,
        _M.AIR,
        _W,
        "8.00",
        "700",
        "167",
        (8, 12),
        handling_fixed="80",
        handling_per_kg="0.10",
    ),
    _card(
        "US-FRU-SEA-MULTIMODAL-WHITE",
        _US,
        "New York",
        BISHKEK,
        _M.SEA_MULTIMODAL,
        _W,
        "2.60",
        "1500",
        "333",
        (45, 65),
        handling_fixed="150",
        handling_per_kg="0.08",
        notes="Sea LCL to Poti/Batumi, truck via Azerbaijan–Caspian–Kazakhstan",
    ),
    # ---------------------------------------------------------------- USA → Moscow (benchmark)
    _card(
        "US-MOW-AIR-WHITE",
        _US,
        "New York / Los Angeles",
        MOSCOW,
        _M.AIR,
        _W,
        "9.00",
        "800",
        "167",
        (8, 14),
        handling_fixed="100",
        handling_per_kg="0.10",
    ),
    _card(
        "US-MOW-SEA-MULTIMODAL-WHITE",
        _US,
        "New York",
        MOSCOW,
        _M.SEA_MULTIMODAL,
        _W,
        "2.80",
        "1800",
        "333",
        (45, 60),
        handling_fixed="150",
        handling_per_kg="0.08",
    ),
    # ---------------------------------------------------------------- UAE → Bishkek
    _card(
        "AE-FRU-AIR-CARGO",
        _AE,
        "Dubai",
        BISHKEK,
        _M.AIR,
        _C,
        "3.60",
        "150",
        "167",
        (3, 6),
        multipliers=_AIR_CARGO_MULTIPLIERS,
    ),
    _card(
        "AE-FRU-AUTO-STANDARD-CARGO",
        _AE,
        "Dubai",
        BISHKEK,
        _M.AUTO_STANDARD,
        _C,
        "2.30",
        "120",
        "200",
        (14, 22),
        multipliers=_CARGO_MULTIPLIERS,
        notes="Truck via Bandar Abbas – Turkmenistan – Uzbekistan",
    ),
    _card(
        "AE-FRU-AIR-WHITE",
        _AE,
        "Dubai",
        BISHKEK,
        _M.AIR,
        _W,
        "3.40",
        "400",
        "167",
        (3, 6),
        handling_fixed="80",
        handling_per_kg="0.10",
    ),
    _card(
        "AE-FRU-AUTO-STANDARD-WHITE",
        _AE,
        "Dubai",
        BISHKEK,
        _M.AUTO_STANDARD,
        _W,
        "2.10",
        "500",
        "250",
        (14, 22),
        handling_fixed="80",
        handling_per_kg="0.08",
    ),
    # ---------------------------------------------------------------- UAE → Moscow (benchmark)
    _card(
        "AE-MOW-AIR-WHITE",
        _AE,
        "Dubai",
        MOSCOW,
        _M.AIR,
        _W,
        "3.90",
        "450",
        "167",
        (3, 6),
        handling_fixed="100",
        handling_per_kg="0.10",
    ),
    _card(
        "AE-MOW-AUTO-STANDARD-WHITE",
        _AE,
        "Dubai",
        MOSCOW,
        _M.AUTO_STANDARD,
        _W,
        "2.50",
        "600",
        "250",
        (15, 25),
        handling_fixed="100",
        handling_per_kg="0.08",
        notes="Truck via Iran – Caspian (Astara) corridor",
    ),
    # ---------------------------------------------------------------- Vietnam → Bishkek
    _card(
        "VN-FRU-AUTO-STANDARD-CARGO",
        _VN,
        "Ho Chi Minh / Hanoi",
        BISHKEK,
        _M.AUTO_STANDARD,
        _C,
        "3.30",
        "150",
        "200",
        (20, 28),
        multipliers=_CARGO_MULTIPLIERS,
        notes="Truck through China (Pingxiang – Urumqi – Torugart)",
    ),
    _card(
        "VN-FRU-AIR-CARGO",
        _VN,
        "Ho Chi Minh",
        BISHKEK,
        _M.AIR,
        _C,
        "5.80",
        "250",
        "167",
        (6, 9),
        multipliers=_AIR_CARGO_MULTIPLIERS,
    ),
    _card(
        "VN-FRU-AUTO-STANDARD-WHITE",
        _VN,
        "Ho Chi Minh / Hanoi",
        BISHKEK,
        _M.AUTO_STANDARD,
        _W,
        "2.10",
        "500",
        "250",
        (20, 28),
        handling_fixed="80",
        handling_per_kg="0.08",
    ),
    _card(
        "VN-FRU-AIR-WHITE",
        _VN,
        "Ho Chi Minh",
        BISHKEK,
        _M.AIR,
        _W,
        "5.50",
        "600",
        "167",
        (5, 8),
        handling_fixed="80",
        handling_per_kg="0.10",
    ),
    # ---------------------------------------------------------------- Vietnam → Moscow (benchmark)
    _card(
        "VN-MOW-AUTO-STANDARD-WHITE",
        _VN,
        "Ho Chi Minh / Hanoi",
        MOSCOW,
        _M.AUTO_STANDARD,
        _W,
        "2.60",
        "700",
        "250",
        (22, 30),
        handling_fixed="100",
        handling_per_kg="0.08",
    ),
    _card(
        "VN-MOW-AIR-WHITE",
        _VN,
        "Ho Chi Minh",
        MOSCOW,
        _M.AIR,
        _W,
        "6.20",
        "700",
        "167",
        (6, 10),
        handling_fixed="100",
        handling_per_kg="0.10",
    ),
)


def _leg(
    from_hub: str,
    city: str,
    mode: TransportMode,
    rate: str,
    min_charge: str,
    days: tuple[int, int],
    distance_km: int | None,
    *,
    coefficient: str | None = None,
    notes: str = "",
) -> DomesticLegRate:
    coef = coefficient or ("167" if mode is TransportMode.AIR else "250")
    return DomesticLegRate(
        leg_id=f"{from_hub[:3].upper()}-{city.upper()}-{mode.value}",
        from_hub=from_hub,
        destination_city=city,
        transport_mode=mode,
        rate_per_kg_rub=Decimal(rate),
        min_charge_rub=Decimal(min_charge),
        volumetric_coefficient_kg_per_m3=Decimal(coef),
        days_min=days[0],
        days_max=days[1],
        distance_km=distance_km,
        notes=notes,
    )


_T = TransportMode.TRUCK
_A = TransportMode.AIR

DEFAULT_DOMESTIC_LEGS: tuple[DomesticLegRate, ...] = (
    # Bishkek → Russia (through Kazakhstan; no customs border inside the EAEU)
    _leg(BISHKEK, "moscow", _T, "45", "12000", (6, 9), 3700),
    _leg(BISHKEK, "moscow", _A, "140", "15000", (1, 3), None),
    _leg(BISHKEK, "tyumen", _T, "35", "10000", (4, 7), 2100),
    _leg(BISHKEK, "yekaterinburg", _T, "34", "10000", (4, 7), 2300),
    _leg(BISHKEK, "yekaterinburg", _A, "130", "15000", (1, 3), None),
    _leg(BISHKEK, "novosibirsk", _T, "32", "9000", (3, 6), 1900),
    _leg(BISHKEK, "novosibirsk", _A, "120", "15000", (1, 3), None),
    _leg(BISHKEK, "chelyabinsk", _T, "33", "10000", (4, 7), 2100),
    _leg(BISHKEK, "omsk", _T, "30", "9000", (3, 6), 1600),
    _leg(BISHKEK, "kazan", _T, "40", "11000", (5, 8), 3000),
    _leg(BISHKEK, "saint_petersburg", _T, "50", "13000", (7, 10), 4400),
    _leg(BISHKEK, "saint_petersburg", _A, "150", "15000", (1, 3), None),
    _leg(BISHKEK, "krasnodar", _T, "52", "13000", (7, 11), 4300),
    _leg(BISHKEK, "samara", _T, "38", "11000", (5, 8), 2700),
    _leg(BISHKEK, "krasnoyarsk", _T, "36", "10000", (4, 7), 2600),
    # Moscow → Russia (benchmark route on-carriage)
    _leg(MOSCOW, "moscow", _T, "4", "2500", (0, 1), 30, notes="Local delivery inside Moscow"),
    _leg(MOSCOW, "tyumen", _T, "18", "6000", (3, 5), 2100),
    _leg(MOSCOW, "yekaterinburg", _T, "15", "6000", (2, 4), 1800),
    _leg(MOSCOW, "novosibirsk", _T, "22", "7000", (4, 6), 3300),
    _leg(MOSCOW, "chelyabinsk", _T, "16", "6000", (3, 5), 1800),
    _leg(MOSCOW, "omsk", _T, "20", "6500", (4, 6), 2700),
    _leg(MOSCOW, "kazan", _T, "10", "4000", (1, 3), 800),
    _leg(MOSCOW, "saint_petersburg", _T, "8", "3500", (1, 2), 700),
    _leg(MOSCOW, "krasnodar", _T, "12", "4500", (2, 3), 1350),
    _leg(MOSCOW, "samara", _T, "12", "4500", (2, 3), 1050),
    _leg(MOSCOW, "krasnoyarsk", _T, "26", "8000", (5, 7), 4100),
)

DEFAULT_FALLBACK_DOMESTIC: dict[str, DomesticLegRate] = {
    BISHKEK: _leg(
        BISHKEK,
        "unknown",
        _T,
        "48",
        "12000",
        (7, 12),
        None,
        notes="Fallback rate for cities without a configured leg",
    ),
    MOSCOW: _leg(
        MOSCOW,
        "unknown",
        _T,
        "20",
        "6000",
        (3, 7),
        None,
        notes="Fallback rate for cities without a configured leg",
    ),
}

__all__ = [
    "BISHKEK",
    "DEFAULT_CORRIDORS",
    "DEFAULT_DOMESTIC_LEGS",
    "DEFAULT_FALLBACK_DOMESTIC",
    "MOSCOW",
]
